config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users do
    get 'confirm_otp_sent', on: :collection
    get 'verify_otp', on: :member
    post 'process_otp_verification', on: :member
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :phone_number, presence: true

  def valid_otp?(entered_otp)
    return false if otp.nil? || verified?

    otp == entered_otp
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    if resource.save
      set_flash_message! :notice, :signed_up

      otp = generate_otp
      resource.update(otp: otp)

      twilio_service = TwilioService.new
      twilio_service.send_otp(resource.phone_number, otp)

      @user = resource

      redirect_to verify_otp_user_path(@user), notice: 'An OTP is sent to your phone number.'
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :phone_number)
  end

  def generate_otp
    rand(10000..99990).to_s.rjust(5, '0')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def verify_otp
    @user = current_user
  end

  def process_otp_verification
    entered_otp = params[:user][:otp_code]
    @user = current_user
    if current_user.valid_otp?(entered_otp)
      current_user.update(verified: true)
      redirect_to root_path, notice: 'OTP verification successful. Your account is now verified.'
    else
      flash[:alert] = 'Invalid OTP. Please try again.'
      render :verify_otp
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/home/index.erb
<h1>Welcome to my application!</h1>
<%if current_user.verified?%>
  <p>Your account is verified</p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SMSNotificationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="flash <%= type %>">
        <%= message %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/verify_otp.html.erb
<h2>Enter OTP to verify your account</h2>

<%= form_with(model: @user, url: process_otp_verification_user_path(@user), method: :post) do |form| %>
  <div class="field">
    <%= form.label :otp_code %>
    <%= form.text_field :otp_code, autofocus: true, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= form.submit 'Verify OTP' %>
  </div>
<% end %>